### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by sujkh85** [szwang/recordrtc-react#2]
try recordrtc-react
npm install(ok)
 
npm start(error)

```
ERROR in ./src/app.js
Module build failed: ReferenceError: Unknown plugin "react-hot-loader/babel" specified in "/Users/dev/.babelrc" at 3, attempted to resolve relative to "/Users/dev"
    at /Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/dev/recordrtc-react/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/dev/recordrtc-react/node_modules/babel-loader/lib/index.js:155:20)
 @ multi main
webpack built e4ef73f93c9985a1616a in 2230ms
Hash: e4ef73f93c9985a1616a
Version: webpack 1.14.0
Time: 2230ms
        Asset    Size  Chunks       Chunk Names
    bundle.js  100 kB       0       main
bundle.js.map  109 kB       0       main
chunk    {0} bundle.js, bundle.js.map (main) 76 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] ./~/html-entities/lib/html5-entities.js 49 kB {0} [built]
    [2] ./~/ansi-html/index.js 4.26 kB {0} [built]
    [3] ./~/ansi-regex/index.js 135 bytes {0} [built]
    [4] ./~/html-entities/index.js 231 bytes {0} [built]
    [5] ./~/html-entities/lib/html4-entities.js 6.57 kB {0} [built]
    [6] ./~/html-entities/lib/xml-entities.js 2.98 kB {0} [built]
    [7] ./~/strip-ansi/index.js 161 bytes {0} [built]
    [8] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} [built]
    [9] (webpack)-hot-middleware/client.js 6.68 kB {0} [built]
   [10] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
   [11] (webpack)/buildin/module.js 251 bytes {0} [built]

ERROR in ./src/app.js
Module build failed: ReferenceError: Unknown plugin "react-hot-loader/babel" specified in "/Users/dev/.babelrc" at 3, attempted to resolve relative to "/Users/dev"
    at /Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/dev/recordrtc-react/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/dev/recordrtc-react/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/dev/recordrtc-react/node_modules/babel-loader/lib/index.js:155:20)
 @ multi main
```

**Comment by rickycodes** [comment]
@sujkh85 `ReferenceError: Unknown plugin "react-hot-loader/babel"`

looks like you're missing some things npm _should_ have installed
